### ISSUE TITLE
How to use Hive TypeAdapter generation along json annotation?

### ISSUE THREAD

**Issue by ildoc** [hivedb/hive#288]
**Question**
I'm using json_annotation to serialize/deserialize my objects, so they look like this

```dart
import 'package:flutter/material.dart';
import 'package:json_annotation/json_annotation.dart';

part 'my_type.g.dart';

@JsonSerializable()
@immutable
class MyType {
  final int id;
  final String code;
  final String description;

  MyType({
    @required this.id,
    @required this.code,
    @required this.description,
  });

  MyType copyWith({
    int id,
    String code,
    String description,
  }) {
    return MyType(
      id: id ?? this.id,
      code: code ?? this.code,
      description: description ?? this.description,
    );
  }

  factory MyType.fromJson(Map<String, dynamic> json) =>
      _$MyTypeFromJson(json);
  Map<String, dynamic> toJson() => _$MyTypeToJson(this);
}
```

I've tried to add `@HiveType()` decorators as shown [here](https://docs.hivedb.dev/#/custom-objects/generate_adapter?id=example) but when I generate the code with build_runner the generated partial class contains only `fromJson` and `toJson`

Does hive's TypeAdapter generation get along json_annotation in some way or have I to use different classes?

**Version**
 - Platform: iOS, Android, Windows
 - Flutter version: 1.17.0
 - Hive version: ^1.4.1+1

**Comment by mccidi** [comment]
Did you add a typeId to the annotation?
Like @HiveType(typeId: 0)

**Comment by Andreigr0** [comment]
It should be closed by now as it generates properly

**Comment by ninoaquinas** [comment]
What's the solution for this question? Is there any specific sequence of decorator that I have to follow between `@JsonSerializable()` and `@HiveType()`?

**Comment by Andreigr0** [comment]
@ninoaquinas no, you don't have to. Just write one after another and then run build runner

**Comment by MarlonDSC** [comment]
Make sure you have these dependencies

```yaml

    dependencies:
      flutter:
        sdk: flutter
      hive: ^2.0.4
      json_annotation: ^4.0.1

    dev_dependencies:
      hive_generator: ^1.1.1
      json_serializable: ^4.1.3
      build_runner: ^2.0.4
```
