### ISSUE TITLE
sdk depends on path 1.7.0 and hive >=0.4.1 <1.4.0-dev depends on path >=1.6.0 <1.7.0

### ISSUE THREAD

**Issue by jpaulo789b** [hivedb/hive#289]
**Question**
How to solve this?

**Code sample**
```dart
Running "flutter pub get" in app_treino...                      
Because every version of flutter_test from sdk depends on path 1.7.0 and hive >=0.4.1 <1.4.0-dev depends on path >=1.6.0 <1.7.0, flutter_test from sdk is incompatible with hive >=0.4.1 <1.4.0-dev.

So, because app_treino depends on both hive 1.2.0 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because app_treino depends on both hive 1.2.0 and flutter_test any from sdk, version solving failed.)
exit code 1
```
my pubspeck

```
name: app_treino
description: Um projeto feito em flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  mobx: ^1.0.2+2
  flutter_mobx: ^1.0.1
  google_fonts: ^0.4.0
  get_it: ^4.0.1
  cupertino_icons: ^0.1.3
  responsive_scaffold: ^1.3.0+2
  retrofit: any
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  url_launcher: ^5.4.2
  cached_network_image: ^2.1.0+1
  easy_localization: ^2.1.0+2
  shared_preferences: ^0.5.6+3
  video_player: ^0.10.8+1
  rounded_loading_button: ^1.0.0
  after_layout: ^1.0.7+2
  fluro: ^1.6.3
  moor_flutter: ^2.1.1
  pin_code_fields: ^2.5.1
  carousel_slider: ^2.0.0
  awesome_card: ^1.1.0
  flutter_skeleton: ^0.1.0+1
  hive: 1.2.0
  hive_flutter: any
  path_provider: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1
  hive_generator: any
  mobx_codegen: ^1.0.2
  moor_generator: ^2.4.0
  retrofit_generator: any

flutter:

  uses-material-design: true

  assets:
    - google_fonts/
    - assets/applogo/
    - assets/langs/
```
