### ISSUE TITLE
Bump dartx version in generator 

### ISSUE THREAD

**Issue by essarn** [hivedb/hive#335]
There is a version conflict when using `hive_generator` with `timetable` because `dartx` version `^0.3.0` is required. Can the version be bumped to resolve this version conflict?

**Comment by Reprevise** [comment]
The `master` branch has fixed this issue. In your pubspec, make sure you have these lines:

```yaml
dependencies:
  hive:
  hive_flutter:
    git:
      url: git://github.com/hivedb/hive.git
      path: hive_flutter

dev_dependencies:
  hive_generator:
    git:
      url: git://github.com/hivedb/hive.git
      path: hive_generator
```

When this package gets updated on pub, you can then use the version number. Until then, use the master channel on Git.
