### ISSUE TITLE
Version solving failed between flutter_driver and hive_flutter

### ISSUE THREAD

**Issue by ram231** [hivedb/hive#359]
**Steps to Reproduce**
Create a new project
add `hive_flutter` as a dependencies
add `flutter_driver` as dev_dependencies
**Code sample**
**pubspec.yaml**
```yml
dependencies:
  flutter:
    sdk: flutter
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
```
```sh
# Output
$ flutter pub get
Because every version of flutter_driver from sdk depends on path 1.7.0 and hive_flutter >=0.3.0-dev depends on path >=1.6.0 <1.7.0, flutter_driver from sdk is incompatible with hive_flutter >=0.3.0-dev.
So, because test_project depends on both hive_flutter ^0.3.0+2 and flutter_driver any from sdk, version solving failed.
Running "flutter pub get" in test_project...
pub get failed (1; So, because test_project depends on both hive_flutter ^0.3.0+2 and flutter_driver any from sdk, version solving failed.)

```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [beta]
 - Hive version: [^1.4.1+1]
