### ISSUE TITLE
Unusable dependency incompatible with Flutter Sdk

### ISSUE THREAD

**Issue by luiz-rocha** [hivedb/hive#362]
$ flutter pub get
Running "flutter pub get" in flutter_projects...                
Because every version of flutter_test from sdk depends on path 1.7.0 and hive_flutter >=0.3.0-dev depends on path >=1.6.0 <1.7.0, flutter_test from sdk is incompatible with hive_flutter >=0.3.0-dev.

So, because flutter_projects depends on both hive_flutter ^0.3.0+2 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because flutter_projects depends on both hive_flutter ^0.3.0+2 and flutter_test any from sdk, version solving failed.)
exit code 1

**Version**
Flutter 1.20.0-3.0.pre.25 • channel master • https://github.com/flutter/flutter.git
Framework • revision b946e30c3d (10 days ago) • 2020-06-23 17:58:01 -0700
Engine • revision 2b6c71c4d3
Tools • Dart 2.9.0 (build 2.9.0-18.0.dev 5a6c1e5158)

**pubspec.yaml**
```
dependencies:
  flutter:
    sdk: flutter
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.11
```

Is this repository maintained yet?
Thank you in advance

**Comment by AndroidNils** [comment]
Same issue

**Comment by AndroidNils** [comment]
This was already fixed with b6a4b830ea28aab48a7915c978e0132be2bdd3ed, right?

**Comment by stefanschaller** [comment]
Same issue

**Comment by AndroidNils** [comment]
This works:
```
hive_flutter:
    git:
      url: https://github.com/hivedb/hive.git
      path: hive_flutter
```
