### ISSUE TITLE
Unable to resolve dependencies with hive and hive_generator from git

### ISSUE THREAD

**Issue by theniceboy** [hivedb/hive#385]
**Steps to Reproduce**
Flutter pub is giving me this error:
```
Because every version of hive_generator from git depends on hive from hosted and my_project depends on hive from git, hive_generator from git is forbidden.

So, because my_project depends on hive_generator from git, version solving failed.
```
 after running `flutter pub get` on this `pubspec.yaml`:
```
dependencies:
  hive:
    git:
      url: https://github.com/hivedb/hive.git
      path: hive

dev_dependencies:
  hive_generator:
    git:
      url: git://github.com/hivedb/hive.git
      path: hive_generator
```

**Code sample**
N/A

**Version**
 - Platform: macOS 10.15.6
 - Flutter version: 1.20.0-7.2.pre (beta channel)
 - Dart version: 2.9.0 (build 2.9.0-21.2.beta)
 - Hive version: haven't installed yet

**Comment by marcelgarus** [comment]
This is the intended behavior. The `hive_generator` is also published to pub, so most people that download it will expect to also have to rely on hive from pub instead from some GitHub repository.

**Comment by theniceboy** [comment]
So is there any way to use hive from git while using hive_generator? @marcelgarus

**Comment by marcelgarus** [comment]
Yes, you can use `dependency_overrides:`
```yaml
dependency_overrides:
  hive_generator:
    git:
      url: git://github.com/hivedb/hive.git
      path: hive_generator
```

**Comment by theniceboy** [comment]
@marcelgarus That gave me the same error. This worked:
```yaml
dependencies:
  hive:
    git:
      url: https://github.com/hivedb/hive.git
      path: hive

dev_dependencies:
  hive_generator:
    git:
      url: git://github.com/hivedb/hive.git
      path: hive_generator

dependency_overrides:
  hive:
    git:
      url: git://github.com/hivedb/hive.git
      path: hive
```
not really sure why but everything seems to be working now
