### ISSUE TITLE
Getter not found: 'ENUM' when generating type adapters with the build_runner

### ISSUE THREAD

**Issue by RobinLbt** [hivedb/hive#408]
Hello,

After changing some field names and adding new ones in my model classes, I tried to run 
`flutter pub run build_runner build --delete-conflicting-outputs` to generate new Type Adapters but I get this error :

```[INFO] Generating build script...
[INFO] Generating build script completed, took 412ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 8.4s

[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] ../../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/hive_generator-0.7.1/lib/src/type_adapter_generator.dart:60:76: Error: Getter not found: 'ENUM'.   
 check(element.kind == ElementKind.CLASS || element.kind == ElementKind.ENUM,  
```

Here is the pubspec.yaml : 
```
version: 1.0.0+1

environment:
  sdk: ">=2.9.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.18.0
  provider: ^4.3.1
  hive: ^1.4.3
  hive_flutter: ^0.3.1
  scrollable_positioned_list: ^0.1.6
  logger: ^0.9.1
  analyzer: 0.39.10
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  hive_generator: ^0.7.1
  build_runner: 
  build_test: ^0.10.3`
```

_Note : I intentionally didn't specify a version for the build_runner because otherwise I need to upgrade the dart SDK to 2.10.0 which is not available on the stable channel yet._

## What I've tried

- Removing the changes I've made in the model classes and try again

- Changing versions of the build runner and hive generator

- Delete the cache (`flutter clean`)

- Running `flutter doctor -v` 
output : 

```
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [version 10.0.18362.1016], locale fr-FR)
    • Flutter version 1.20.2 at C:\Users\robin\Documents\flutter
    • Framework revision bbfbf1770c (4 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\robin\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.48.0)
    • VS Code at C:\Users\robin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

I didn't find anything similar on the web
