### ISSUE TITLE
Dependency error in Hive Generator

### ISSUE THREAD

**Issue by vandir** [hivedb/hive#597]
Currently, as written in the documentation, you have to add the following dependencies to use Hive:

```
dependencies:
  hive: ^2.0.0
  hive_flutter: ^1.0.0

dev_dependencies:
  hive_generator: ^1.0.0
  build_runner: ^1.12.1
```
but what you get is:

```
Because build_runner >=1.12.0 depends on build >=2.0.0 <2.1.0 and hive_generator >=0.9.0-nullsafety.0 depends on build ^1.5.2, build_runner >=1.12.0 is incompatible with hive_generator >=0.9.0-nullsafety.0.
```

I think the problem is in the file `pubspec.yaml` of Hive Generator:

<pre>
dependencies:
  <b>build: ^1.5.2</b>
  source_gen: ">=0.9.10+1 <2.0.0"
  hive: ^2.0.0
  analyzer: ">=0.40.0 <2.0.0"
</pre>

`source_gen` now supports `build 2.0.0` so I think you can fix this issue.

If anyone has the same problem please replace the following lines:

```
dev_dependencies:
  hive_generator: ^1.0.0
  build_runner: ^1.12.1
```

with:
```
dev_dependencies:
  hive_generator:
  build_runner:
```

Many thanks!
