### ISSUE TITLE
Because hive_generator >=0.9.0-nullsafety.0 depends on build ^1.5.2 and mobx_codegen 2.0.0-nullsafety.2 depends on build ^2.0.0, hive_generator >=0.9.0-nullsafety.0 is incompatible with mobx_codegen 2.0.0-nullsafety.2.

### ISSUE THREAD

**Issue by hsnbsst** [hivedb/hive#617]
I am having such a problem, what can I do?

**Steps to Reproduce**
Because hive_generator >=0.9.0-nullsafety.0 depends on build ^1.5.2 and mobx_codegen 2.0.0-nullsafety.2 depends on build ^2.0.0, hive_generator >=0.9.0-nullsafety.0 is incompatible with mobx_codegen 2.0.0-nullsafety.2.

And because no versions of mobx_codegen match >2.0.0-nullsafety.2 <3.0.0, hive_generator >=0.9.0-nullsafety.0 is incompatible with mobx_codegen ^2.0.0-nullsafety.2.

So, because mafya depends on both mobx_codegen ^2.0.0-nullsafety.2 and hive_generator ^1.0.0, version solving failed.
pub get failed (1; So, because mafya depends on both mobx_codegen ^2.0.0-nullsafety.2 and hive_generator ^1.0.0, version solving failed.)
exit code 1

**Code sample**
```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  badges: ^2.0.0-nullsafety.1
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  device_info_plus: ^1.0.0
  dio: ^4.0.0-prev3
  easy_localization: ^3.0.0
  firebase_analytics: ^8.0.0-dev.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  firebase_crashlytics: ^1.0.0
  firebase_messaging: ^9.1.0
  flare_flutter: ^3.0.0-nullsafety.1
  flutter_html: ^2.0.0-nullsafety.0
  flutter_screenutil: ^5.0.0-nullsafety.11
  flutter_svg: ^0.21.0-nullsafety.0
  fluttertoast: ^8.0.3
  font_awesome_flutter: ^9.0.0
  get_it: ^6.0.0
  google_fonts: ^2.0.0
  json_annotation: ^4.0.1
  lottie: ^1.0.1
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  mobx: ^2.0.0-nullsafety.5
  flutter_mobx: ^2.0.0-nullsafety.3
  package_info: ^2.0.0
  percent_indicator: ^3.3.0-nullsafety.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  shared_preferences: ^2.0.5
  simple_tooltip: ^0.1.16
  transparent_image: ^2.0.0
  url_launcher: ^6.0.2
  uuid: ^3.0.1
  intl: ^0.17.0
  pull_to_refresh: 1.6.4-nullsafety.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  json_serializable: ^4.0.1
  mobx_codegen: ^2.0.0-nullsafety.2
  hive_generator: ^1.0.0
```

**Version**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on Mac OS X 10.15.7 19H524 darwin-x64, locale tr-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)

• No issues found!
hsnbsst@Hasan-MacBook-Pro mafya %

**Comment by return-main** [comment]
The fix is already available on [GitHub](https://github.com/hivedb/hive/commit/0a66d8668d199a09a82c2d49a3d914fef7cb14c5), so change your pubspec.yaml dev_dependencies to:
```yaml
dev_dependencies:
  hive_generator:  # ^1.0.0 with a dependency fix
    git:
      url: https://github.com/hivedb/hive.git
      path: hive_generator/
      ref: 0a66d8668d199a09a82c2d49a3d914fef7cb14c5
```
