### ISSUE TITLE
'fromJson' methods being generated with wrong names

### ISSUE THREAD

**Issue by daybson** [hivedb/hive#667]
**Steps to Reproduce**
I have two classes (Custo and Item), where Item uses Custo. The json serialization generated to Custo is named like 'CustoFromJson', but the generator produces a name like Custo.fromJson inside Item. 

Am I doing something wrong?

**Code sample**
```
import 'package:hive/hive.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:json_annotation/json_annotation.dart';

part 'custo.g.dart';

@JsonSerializable()
@HiveType(typeId: 5)
class Custo {
  Custo();

  @HiveField(0)
  int? id;

  @HiveField(1)
  String? nome;

  @HiveField(2)
  String? descricao;

  @HiveField(3)
  int? quantidade;

  @HiveField(4)
  String? unidadeMedida;

  @HiveField(5)
  bool? original;
}


import 'package:hive_flutter/hive_flutter.dart';
import 'package:defensores/model/rpg/custo/custo.dart';
import 'package:defensores/model/rpg/inventario/item_status.dart';
import 'package:hive/hive.dart';
import 'package:json_annotation/json_annotation.dart';
part 'item.g.dart';

@JsonSerializable()
@HiveType(typeId: 14)
class Item {
  Item();

  @HiveField(0)
  int? id;

  @HiveField(1)
  String? nome;

  @HiveField(2)
  String? descricao;

  @HiveField(3)
  Custo? custo;

  @HiveField(4)
  ItemStatus? status;
}
```
Running script:
`flutter pub run build_runner build --delete-conflicting-outputs`

Methods generated in CustoAdapter:
```
Custo _$CustoFromJson(Map<String, dynamic> json) ...
Map<String, dynamic> _$CustoToJson(Custo instance) ....
```

Methods expected in ItemAdapter:
```
Item _$ItemFromJson(Map<String, dynamic> json) {
  return Item()
    ..id = json['id'] as int?
    ..nome = json['nome'] as String?
    ..descricao = json['descricao'] as String?
    ..custo = json['custo'] == null
        ? null
        : Custo.fromJson(json['custo'] as Map<String, dynamic>)
    ..status = json['status'] == null
        ? null
        : ItemStatus.fromJson(json['status'] as Map<String, dynamic>);
}
```

**Version**
 - Platform: Windows
 - Flutter 2.3.0-2.0.pre.241 • channel master
 - Framework • revision c410ae35d7 (27 hours ago) • 2021-05-17 05:54:02 -0400
 - Engine • revision 26e217e6c3
 - Tools • Dart 2.14.0
 - Hive version: ^2.0.4
 - yaml:

```
dependencies:
  flutter:
    sdk: flutter 
  cloud_firestore: ^2.1.0
  cupertino_icons: ^1.0.3 
  dropdown_search: ^0.6.1
  #firebase_admob:
  firebase_analytics: ^8.0.4
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4 
  flutter_spinbox: ^0.5.2
  get: ^4.1.4
  get_it: ^7.1.3
  google_sign_in: ^5.0.3
  platform: ^3.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  json_annotation: ^4.0.1
  package_info_plus: ^1.0.1 
  search_choices: ^2.0.3 
  build_runner: ^2.0.3
  json_serializable: ^4.1.2
  hive_generator: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter 

```
