### ISSUE TITLE
How to add new required and non-nullable field to model with existing data?

### ISSUE THREAD

**Issue by comatory** [hivedb/hive#707]
**Question**
I have a data model `User`. My application already stores the data on disk. I added new field `uuid` with type `String`. This field is required by the class because from now on, it is a required field.
The problem of course is that when I launch application, the saved user model instances do not contain `uuid` (the data needs to be fetched from server). My `uuid` attribute (field) is created from list of `ids`.

I get a runtime error:

```
Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast
E/flutter ( 2024): #0      ShiftAdapter.read (package:subscription_commute_driver_app_flutter/models/user.g.dart:21:23)
E/flutter ( 2024): #1      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:326:33)
E/flutter ( 2024): #2      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:274:26)
E/flutter ( 2024): #3      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21:26)
E/flutter ( 2024): #4      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42:12)
```

Is there a way to have a user model class that needs to have  `uuid` field to be a required field? Because if I change the field to be nullable, the application runs fine, then it creates and saves new instance and I can revert it to `required` field.

I kind of see the point that `uuid` should be nullable from the perspective of existing & stored data but architectually, the `uuid` attribute should always be available. I'm not sure if HiveDB has some concept of migrations, otherwise in production this would mean to release a version where `uuid` would be nullable with the overhead of guard checks everywhere in code. Next version I could probably make the `uuid` field required and ppl would not get runtime errors (but it could still happen when someone updates app but did not open it before).

**Code sample**
```dart
  class User extends Equatable {
     const User({
        required this.id,
        required this.ids,
        required this.uuid,
     });
  // ...
  static User fromJSON(dynamic json) {
    final id = (json['id'] as String?) ?? '';
    final ids = (json['ids'] as List? ?? <String>[])
        .map((id) => id as String? ?? '')
        .toList();
    final uuid = ids.join('');

    return User(
        id: id,
        ids: ids,
        uuid: uuid);
  }

  @HiveField(0)
  final String id;
  @HiveField(4)
  final List<String> ids;
  @HiveField(5)
  final String uuid;

```

**Version**
 - Platform: Android
 - Flutter version: 
 ```
 Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (3 weeks ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
```
 - Hive version:
 ```
   hive:
    dependency: "direct main"
    description:
      name: hive
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  hive_generator:
    dependency: "direct dev"
    description:
      name: hive_generator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
```
