### ISSUE TITLE
incompatible with retrofit

### ISSUE THREAD

**Issue by subzero911** [hivedb/hive#772]
```
Running "flutter pub get" in supster...                         
Because retrofit_generator >=2.0.1+1 depends on analyzer ^2.0.0 and hive_generator >=1.0.1 depends on analyzer ^1.0.0, retrofit_generator >=2.0.1+1 is incompatible with hive_generator >=1.0.1.
```

please update dependencies!

**Comment by pishguy** [comment]
@subzero911 

did you try `retrofit_generator` without specifying any version?

**Comment by subzero911** [comment]
> @subzero911
> 
> did you try `retrofit_generator` without specifying any version?

It's a generally bad practice, we should always specify the latest version, or else it will took any version currenlty cached on local machine! It may lead to unexpected results.

i currently used override_dependencies to supress the error, but it's a temporary solution.
```yaml
dependency_overrides:
  # conflict between hive_generator && retrofit_generator
  analyzer: ^2.0.0
  meta: ^1.7.0
```
