### ISSUE TITLE
push Update hive _generator analyzer to pub.dev

### ISSUE THREAD

**Issue by davidAg9** [hivedb/hive#774]
**Steps to Reproduce**
pub spec.yaml is complaining because some of my packages use analyzer 2 and hive Is using analyzer 1 so it is unable to resolve my dependencies correctly .

**Version**
 - Platform: iOS, Android,
 - Flutter version: [stable]
 - Hive version: [2.0.4]

**Comment by westy92** [comment]
I need this resolved as well.

**Comment by flukejones** [comment]
I've also been stuck on analyzer < 2.0.0 due to this.

**Comment by ElZombieIsra** [comment]
Same here. I'm not certain if we can override the dependency or something meanwhile this is updated but if we can, please let me know

**Comment by flukejones** [comment]
> Same here. I'm not certain if we can override the dependency or something meanwhile this is updated but if we can, please let me know

```
  #hive_generator: ^1.1.0
  hive_generator:
    git:
      url: https://github.com/hivedb/hive.git
      ref: master
      path: hive_generator
```

is a temporary fix. Not really one I want to leave in production though.

**Comment by ElZombieIsra** [comment]
@flukejones Thanks for the help. Hope to remove this sooner than later.

**Comment by westy92** [comment]
@flukejones thanks for the tip. It can be made a little more "stable" by pointing at a specific commit:

```yaml
  hive_generator:
    git:
      url: https://github.com/hivedb/hive.git
      ref: a0e0474
      path: hive_generator
```
